django/01-introduction/apps/discogs/urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template

from discogs.views import *

urlpatterns = patterns('',
    url(r'^search/$', discogs_search, name='discogs-search'),
)

django/01-introduction/apps/portfolio/urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template

from portfolio.views import *

urlpatterns = patterns('',
    url(r'^$', project_list, name='portfolio-project-list'),
    url(r'^project/(?P<pk>\d+)/$', project_detail, name='portfolio-project-detail'),
    url(r'^project/(?P<pk>\d+)/comments/$', comment_list, name='portfolio-project-comments'),

)

django/01-introduction/apps/twitter/urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template

from twitter.views import *

urlpatterns = patterns('',
    url(r'^search/$', twitter_search, name='twitter-search'),
)

django/01-introduction/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.views.generic.simple import direct_to_template

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
                       
    url(r'^$', direct_to_template, {'template': 'home.html'}, name='home'),
    
    url(r'^contact/$', direct_to_template, {'template': 'contact.html'}, name='contact'),
    
    # project urls
    url(r'^twitter/', include('twitter.urls')),
    url(r'^discogs/', include('discogs.urls')),
    url(r'^portfolio/', include('portfolio.urls')),
    
    # admin urls
    url(r'^admin/', include(admin.site.urls)),
)




if settings.SERVE_MEDIA:
    urlpatterns += patterns("",
        url(r"", include("staticfiles.urls")),
)
    
if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
)

django/01-introduction/apps/discogs/models.py
from django.db import models

# Create your models here.

django/01-introduction/apps/portfolio/models.py
"""
.. module:: models
   :platform: Unix, Windows
   :synopsis: Portfolio Models.

.. moduleauthor:: Andrew Carter <andrew@invalid.com>

"""

from django.db import models

# Create your models here.
class Project(models.Model):
    """Project Definition
    
    ::
    
        def whatever(self):
            retorn False
    """
    
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True, null=True)
    active = models.BooleanField(default=False)
    date = models.DateField(blank=True, null=True)
    """Docstring for class attribute date."""
    
    client = models.ForeignKey('Client', blank=True, null=True)
    media = models.ManyToManyField('Media', blank=True, null=True)
    
    class Meta:
        verbose_name = 'Project'
        verbose_name_plural = 'Projects'
        ordering = ('name', )
        
    def __unicode__(self):
        return '%s' % self.name
    
    
    def get_absolute_url(self):
        return '/portfolio/project/%s/' % self.pk


class Image(models.Model):
    
    file = models.ImageField(upload_to='images')
    
    name = models.CharField(max_length=200, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    
    project = models.ForeignKey('Project', blank=True, null=True)
    
    
    class Meta:
        verbose_name = 'Image'
        verbose_name_plural = 'Images'
        
    def __unicode__(self):
        return '%s - %s' % (self.name, self.file)
    
    
    






class Client(models.Model):
    
    name = models.CharField(max_length=200)
    website = models.URLField(blank=True, null=True)
    
    class Meta:
        verbose_name = 'Client'
        verbose_name_plural = 'Clients'
        ordering = ('name', )
        
    def __unicode__(self):
        return '%s' % self.name


class Media(models.Model):
    
    name = models.CharField(max_length=200)
    
    class Meta:
        verbose_name = 'Media'
        verbose_name_plural = 'Media'
        ordering = ('name', )
        
    def __unicode__(self):
        return '%s' % self.name
    
    
   
   
class Comment(models.Model):

    username = models.CharField(max_length=200)
    text = models.TextField()
    created = models.DateTimeField(auto_now=True)
    
    project = models.ForeignKey('Project', blank=True, null=True)
    
    class Meta:
        verbose_name = 'Comment'
        verbose_name_plural = 'Comments'
        ordering = ('-created',)
        
    def __unicode__(self):
        return '%s | %s' % (self.username, self.created)


   
    
    

django/01-introduction/apps/discogs/views.py
from django.http import HttpResponse
from django.template.response import TemplateResponse

from lib.api import Discogs

"""
def twitter_search(request):
    print request    
    html = '<h1>Hallo</h1>'
    return HttpResponse(html)
"""

def discogs_search(request):
    
    query = request.GET.get('query', None)
    
    print 'Query: %s' % query
    
    release = None
    """"""
    if query:
        d = Discogs()
        result = d.search(query)
        release = result
        
        print release
    
    data = {
            'title': 'My Title Discogs',
            'query': query,
            'release': release
            }
    
    return TemplateResponse(request, 'discogs/search.html', data)

django/01-introduction/apps/portfolio/views.py
from django.http import HttpResponse
from django.template.response import TemplateResponse
from django.shortcuts import get_object_or_404
import json

from portfolio.models import Project, Client



def project_list(request):
    
    projects = Project.objects.all()
    clients = Client.objects.all()

    data = {
            'projects': projects,
            'clients': clients
            }
    
    return TemplateResponse(request, 'portfolio/project_list.html', data)

def project_detail(request, pk):
    
    project = get_object_or_404(Project, pk=pk)

    data = {
            'project': project
            }
    
    return TemplateResponse(request, 'portfolio/project_detail.html', data)



def comment_list(request, pk):
    
    project = get_object_or_404(Project, pk=pk)
    content = []
    
    for comment in project.comment_set.all():
        c = {
             'username': comment.username,
             'text': comment.text,
             }
        content.append(c)
        
    import time
    time.sleep(1)
    
    return HttpResponse(json.dumps(content), content_type='application/json')

django/01-introduction/apps/twitter/views.py
from django.http import HttpResponse
from django.template.response import TemplateResponse

from lib.api import Twitter

"""
def twitter_search(request):
    print request    
    html = '<h1>Hallo</h1>'
    return HttpResponse(html)
"""

def twitter_search(request):
    
    query = request.GET.get('query', None)
    
    print 'Query: %s' % query
    
    tweets = None
    
    if query:
        t = Twitter()
        result = t.search(query)
        tweets = result['results']
    
    data = {
            'title': 'My Title',
            'query': query,
            'tweets': tweets
            }
    
    return TemplateResponse(request, 'twitter/search.html', data)

django/01-introduction/apps/discogs/templates/discogs/search.html
{% extends "base.html" %}
{% load sekizai_tags webdesign %}

{% block "main" %}
<h1>{{ title }}</h1>
<p>Your query is: {{ query }}</p>


{% if release %}

	<h3>{{ release.title }}</h3>
	
	{% for track in release.tracklist %}
	
		<h4><small>{{ track.position }}</small> {{ track.title }}</h4>
	
	{% endfor %}
	
{% else %}
	<div class="alert alert-warning">
		<p>No results</p>
	</div>

{% endif %}




{% endblock %}

{% block "sidebar" %}
<form action="" method="get">
	<fieldset>
		<legend>
			<h4>Search<i class="icon-search pull-right"></i></h4>
		</legend>
		<label>Query</label>
		<input type="text" name="query" {% if query %}value="{{ query }}"{% endif %} placeholder="Search query…">
		<span class="help-block">Example: "4268905"</span>
		<button type="submit" class="btn btn-primary pull-right">
			Search
		</button>
	</fieldset>
</form>
{% endblock %}

django/01-introduction/apps/discogs/templates/discogs/tweet_entry.html
<div class="tweet">
	
	<h3><small>From: </small>{{ tweet.from_user }} <small>To: </small>{{ tweet.to_user }}</h3>
	<p>{{ tweet.text|urlize }}</p>
	
</div>

django/01-introduction/apps/portfolio/templates/portfolio/project_detail.html
{% extends "base.html" %}

{% load thumbnail %}

{% block "main" %}


<div class="project">
	
	<h1 style="color: green"><i class="icon-ok-sign"></i> {{ project.name }}</h1>
	
	{% if project.description  %}
	{{ project.description|linebreaks }}
	{% endif %}
	
	<h2><i class="icon-tags"></i></h2>
	
	
	{% if project.client %}
	{{ project.client.name }}{{ project.client.url }}
	{% else %}
	<p>no client..</p>
	{% endif %}
		

	{% for media in project.media.all %}
	{{ media.name }}
	{% endfor %}

	
	{% for image in project.image_set.all %}
	<img src="{% thumbnail image.file 100x100 upscale crop %}" >
	{% endfor %}
	
	
</div>
	



{% endblock %}




{% block "sidebar" %}

<h2 onclick="loadComments()"><i class="icon-comments"></i> Load Comments</h2>
<p>Please click every 5 seconds</p>


<div id="comments_container">
	loading...
</div>

{% endblock %}

django/01-introduction/apps/portfolio/templates/portfolio/project_list.html
{% extends "base.html" %}

{% load thumbnail %}

{% block "main" %}

{% for project in projects %}
<div class="project">
	
	<h1 style="color: green"><i class="icon-ok-sign"></i> {{ project.name }}</h1>
	
	{% if project.description  %}
	{{ project.description|linebreaks }}
	{% endif %}
	
	<h2><i class="icon-align-center"></i></h2>
	
	
	{% if project.client %}
	{{ project.client.name }}{{ project.client.url }}
	{% else %}
	<p>no client..</p>
	{% endif %}
		

	{% for media in project.media.all %}
	{{ media.name }}
	{% endfor %}

	
	{% for image in project.image_set.all %}
	<img src="{% thumbnail image.file 100x100 upscale crop %}" >
	{% endfor %}
	
	
</div>
	

{% endfor %}

{% endblock %}




{% block "sidebar" %}


<div class="client-list">

<dl>
	{% for client in clients %}
		<dt>{{ client.name }}</dt>
		<dd>{% if client.website %}<a href="{{ client.website }}"><i class="icon-external-link" ></i> Website<a>{% endif %}</dd>	
	{% endfor %}		
</dl>

</div>


{% endblock %}

django/01-introduction/apps/twitter/templates/twitter/search.html
{% extends "base.html" %}
{% load sekizai_tags webdesign %}

{% block "main" %}
<h1>{{ title }}</h1>
<p>Your query is: {{ query }}</p>


{% if tweets %}

	{% for tweet in tweets %}

		{% include "twitter/tweet_entry.html" %}
		
	{% endfor %}
	
{% else %}
	<div class="alert alert-warning">
		<p>No results</p>
	</div>

{% endif %}




{% endblock %}

{% block "sidebar" %}
<form action="" method="get">
	<fieldset>
		<legend>
			<h4>Search<i class="icon-search pull-right"></i></h4>
		</legend>
		<label>Query</label>
		<input type="text" name="query" {% if query %}value="{{ query }}"{% endif %} placeholder="Search query…">
		<span class="help-block">Example: "from:twitterapi"</span>
		<button type="submit" class="btn btn-primary pull-right">
			Search
		</button>
	</fieldset>
</form>
{% endblock %}

django/01-introduction/apps/twitter/templates/twitter/tweet_entry.html
<div class="tweet">
	
	<h3><small>From: </small>{{ tweet.from_user }} <small>To: </small>{{ tweet.to_user }}</h3>
	<p>{{ tweet.text|urlize }}</p>
	
</div>

django/01-introduction/templates/base.html
{% load sekizai_tags %}
<!doctype html>
<html class="no-js" lang="en">
	<head>
		<meta charset="utf-8">

		<title></title>
		<meta name="description" content="">
		<meta name="author" content="">

		<meta name="viewport" content="width=device-width">

		<link rel="stylesheet" href="{{ STATIC_URL }}css/site.css">
		<link rel="stylesheet" href="{{ STATIC_URL }}css/responsive.css">

		{% render_block "css" %}

		<script src="{{ STATIC_URL }}js/lib/modernizr-2.5.3.min.js"></script>
		<script src="{{ STATIC_URL }}js/lib/jquery-1.9.0.min.js"></script>
		<script src="{{ STATIC_URL }}js/lib/bootstrap/bootstrap-collapse.js"></script>
		
		<script src="{{ STATIC_URL }}js/comments.js"></script>


	</head>
	<body>

		<div class="navbar">
			<div class="navbar-inner">
				{% include "navigation/_main.html" %}
			</div>
		</div>

		<div class="container">

			<header>
				{% block "header" %}{% endblock %}
			</header>

			<section id="global">

				<div class="row">
					<div class="span8">
						{% block "main" %}{% endblock %}
					</div>
					<div class="span4">
						{% block "sidebar" %}{% endblock %}
					</div>
				</div>

			</section>

			<footer>
				{% block "footer" %}{% endblock %}
			</footer>

		</div>

		{% render_block "js" %}

	</body>
</html>

django/01-introduction/templates/contact.html
{% extends "base.html" %}

{% load webdesign %}

{% block "main" %}
<h1>{% lorem 2 w random %}</h1>
{% lorem 4 p random %}
{% endblock %}


{% block "sidebar" %}
<h3>Sidebar</h3>
{% endblock %}

django/01-introduction/templates/home.html
{% extends "base.html" %}
{% load sekizai_tags %}


{% block "main" %}
<h1>Block Main</h1>
{% endblock %}

django/01-introduction/templates/navigation/_main.html
<div class="container">

<button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
</button>

<a class="brand" href="/">site | base</a>

<div class="nav-collapse collapse">
	<ul class="nav">
		<li>
			<a href="/">Home</a>
		</li>
		<li>
			<a href="{% url twitter-search %}">Twitter Search</a>
		</li>
		<li>
			<a href="{% url discogs-search %}">Discogs Search</a>
		</li>
		<li>
			<a href="{% url portfolio-project-list %}">Portfolio</a>
		</li>
	</ul>
</div>


</div>

django/01-introduction/templates/test.html
<!doctype html>
<html class="no-js" lang="en">
	<head>
		<meta charset="utf-8">

		<title></title>
		<meta name="description" content="">
		<meta name="author" content="">

		<meta name="viewport" content="width=device-width">

		<link rel="stylesheet" href="/static/css/bootstrap.css">
		<link rel="stylesheet" href="/static/css/site.css">
		<link rel="stylesheet" href="/static/css/responsive.css">

		<script src="/static/js/lib/modernizr-2.5.3.min.js"></script>
		<script src="/static/js/lib/jquery-1.9.0.min.js"></script>
		<script src="/static/js/lib/bootstrap/bootstrap-collapse.js"></script>

	</head>
	<body>

		<div class="navbar">
			<div class="navbar-inner">
				<div class="container">

					<button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>

					<a class="brand" href="/">site | base</a>

					<div class="nav-collapse collapse">
						<ul class="nav">
							<li>
								<a href="/">Home</a>
							</li>
						</ul>
					</div>

				</div>
			</div>
		</div>

		<div class="container">

			<header>

			</header>

			<section id="global">

				<div class="row">
					<div class="span8">
						<h1>Title</h1>
						<p>text...</p>
					</div>
					<div class="span4">

					</div>
				</div>

			</section>

			<footer>

			</footer>

		</div>

	</body>
</html>